spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3307/listaapi
    username: root
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
      format_sql: true

    properties:
      hibernate:
        show_sql: true
    show-sql: false

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}